name: Input Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose th env to Deploye
        required: true
        default: dev
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploying the app to ${{inputs.environment}}"
