name: Input Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose th env to Deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose the git tag to deploye
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploying the ${{inputs.artifact_tag}} app to ${{inputs.environment}}"
